version: "3.9"
services:
  postgres:
    image: postgres:13.3
    restart: always
    container_name: web-postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"

